let modeloJson1 = [
    {
        id: 1,
        name: 'COSPLAY CAITLYN',
        from: 'Arcane/LOL',
        img: 'img/c1.svg',
        link: '#',
        price: 'R$ 300,99',
    },
    {
        id: 2,
        name: 'COSPLAY MARY SAOTOME',
        from: 'Kakegurui',
        img: 'img/c2.svg',
        link: '#',
        price: 'R$ 300,90',
    },
     {
        id: 3,
        name: 'COSPLAY SHINOBU',
        from: 'Demon Slayer',
        img: 'img/c3.svg',
        link: '#',
        price: 'R$ 200,00',
    },
    {
        id: 4,
        name: 'COSPLAY RAM',
        from: 'Re:Zero',
        img: 'img/c4.svg',
        link: '#',
        price: 'R$ 300,99',
    },
    {
        id: 5,
        name: 'COSPLAY JINX',
        from: 'Arcane/LOL',
        img: 'img/c5.svg',
        link: '#',
        price: 'R$ 200,99',
    },
    {
        id: 6,
        name: 'D.Va',
        from: 'Overwatch',
        img: 'img/c6.svg',
        link: '#',
        price: 'R$ 200,00',
    }
];